// examples/editor-sdk-vue/src/components/Editors.vue
<script>
import {Grammarly, GrammarlyEditorPlugin} from "@grammarly/editor-sdk-vue";
import {demoText, demoClientId} from "./demo";

export default {
  data: () => ({text: demoText, clientId: demoClientId}),
  components: {Grammarly, GrammarlyEditorPlugin},
};
</script>

<template>
  <Grammarly clientId={demoClientId}>
    <div>
      <h2>Textarea</h2>
      <GrammarlyEditorPlugin>
        <textarea v-model="text.textarea" rows={10}></textarea>
      </GrammarlyEditorPlugin>

      <h2>Input</h2>
      <GrammarlyEditorPlugin>
        <input v-model="text.input" id="test-input" size="50"/>
      </GrammarlyEditorPlugin>

      <h2>Contenteditable</h2>
      <GrammarlyEditorPlugin>
        <div contentEditable="true" v-html="text.contenteditable"></div>
      </GrammarlyEditorPlugin>
    </div>
  </Grammarly>
</template>

// examples/editor-sdk-react-stats/src/Editors.js
import React, { useState } from "react";

import { Grammarly, GrammarlyEditorPlugin } from "@grammarly/editor-sdk-react";
import { demoClientId, demoText } from "./demo";
import "./style.css";

const StatsOutput = ({ stats }) => <pre>{JSON.stringify(stats, null, 2)}</pre>;

export const Editors = () => {
  const [stats, setStats] = useState();

  const config = {
    onTextStats: (stats) => setStats(stats),
  };
  return (
    <Grammarly clientId={demoClientId}>
      <h2>Textarea</h2>
      <GrammarlyEditorPlugin config={config}>
        <textarea defaultValue={demoText.textarea} rows={10}></textarea>
      </GrammarlyEditorPlugin>
      {stats && <StatsOutput stats={stats} />}
    </Grammarly>
  );
};
