// examples/editor-sdk-react/src/Editor.js
import React from "react";

import { Grammarly, GrammarlyEditorPlugin } from "@grammarly/editor-sdk-react";
import { demoClientId, demoText } from "./demo";
import "./style.css";

export const Editor = () => {
  return (
    <Grammarly clientId={demoClientId}>
      <h2>Textarea</h2>
      <GrammarlyEditorPlugin>
        <textarea defaultValue={demoText}></textarea>
      </GrammarlyEditorPlugin>
    </Grammarly>
  );
};

// examples/vue-input/src/components/Editor.vue
<script>
import { GrammarlyInput } from "@grammarly/vue-textarea";
import { demoText, demoClientId } from "./demo";

export default {
  data: () => ({ text: demoText, clientId: demoClientId }),
  components: { GrammarlyInput },
};
</script>

<template>
  <GrammarlyInput v-model="text" style="width: 100%" :clientId="clientId" />
</template>
