// examples/react-input/src/Editor.js
import React, { useState } from "react";

import { GrammarlyInput } from "@grammarly/react-textarea";
import { demoClientId, demoText } from "./demo";
import "./style.css";

export const Editor = () => {
  const [value, setValue] = useState(demoText);
  return (
    <div style={{ width: "450px" }}>
      <GrammarlyInput
        clientId={demoClientId}
        value={value}
        onChange={(event) => {
          setValue(event.target.value);
        }}
      />
    </div>
  );
};

// examples/vue-input/src/components/Editor.vue
<script>
import { GrammarlyInput } from "@grammarly/vue-textarea";
import { demoText, demoClientId } from "./demo";

export default {
  data: () => ({ text: demoText, clientId: demoClientId }),
  components: { GrammarlyInput },
};
</script>

<template>
  <GrammarlyInput v-model="text" style="width: 100%" :clientId="clientId" />
</template>
